Array modification (Advance part)
1.insert/ add
2.remove
3.stack
4.split

insert data in 1D 2D 3D....

In [6]:
import numpy as np
arr=np.array([[1,2],[12,4]])
print(arr)
print()
#  with axises non gives flatten 
new_arr=np.insert(arr,1,4,axis=None)
print("with axis Non  ",new_arr)
print()

# with axis 0 which insert values according to row wise
new_arr=np.insert(arr,1,4,axis=0)
print("with axis 0  ",new_arr)
print()

# with axis 1 which insert values according to column wise
new_arr=np.insert(arr,1,4,axis=1)
print("with axis 1  ",new_arr)

print()
# append method
arr=np.array([1,2,4,5])
new=np.append(arr,[6,7,8,9])
print(new)

[[ 1  2]
 [12  4]]

with axis Non   [ 1  4  2 12  4]

with axis 0   [[ 1  2]
 [ 4  4]
 [12  4]]

with axis 1   [[ 1  4  2]
 [12  4  4]]

[1 2 4 5 6 7 8 9]
