In [3]:
import numpy as np
arry1d=np.array([1,4,5,6,7])
print(arry1d)
arry=np.array([[123,2,3,4],[6,7,8,9]])
print(arry)
py_list=[1,2,3,4]
print("python list",py_list*2)
py_list=np.array([1,2,3,4])
print("python list",py_list*2)

[1 4 5 6 7]
[[123   2   3   4]
 [  6   7   8   9]]
python list [1, 2, 3, 4, 1, 2, 3, 4]
python list [2 4 6 8]


In [ ]:
import time
start=time.time()
my_list=[i*2 for i in range(10000)]
print(time.time()-start)


0.0025866031646728516
