In [3]:
import numpy as np
arry1d=np.array([1,4,5,6,7])
print(arry1d)
arry=np.array([[123,2,3,4],[6,7,8,9]])
print(arry)
py_list=[1,2,3,4]
print("python list",py_list*2)
py_list=np.array([1,2,3,4])
print("python list",py_list*2)

[1 4 5 6 7]
[[123   2   3   4]
 [  6   7   8   9]]
python list [1, 2, 3, 4, 1, 2, 3, 4]
python list [2 4 6 8]


In [9]:
import time
start=time.time()
my_list=[i*2 for i in range(10000)]
print(time.time()-start)

import numpy as np
start=time.time()
my_arry=np.arange(100000)*2
print(time.time()-start)


0.002752542495727539
0.002155303955078125


creating array from scratch



In [18]:
import numpy as np
zero=np.zeros((3,4))
print(zero)

one=np.ones((2,3))
print(one)

full=np.full((2,3),"*")
print(full)

random=np.random.random((2,3))
print(random)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[['*' '*' '*']
 ['*' '*' '*']]
[[0.09803614 0.19655361 0.58817357]
 [0.83308658 0.81641987 0.73362803]]
