In [3]:
import numpy as np
arry1d=np.array([1,4,5,6,7])
print(arry1d)
arry=np.array([[123,2,3,4],[6,7,8,9]])
print(arry)
py_list=[1,2,3,4]
print("python list",py_list*2)
py_list=np.array([1,2,3,4])
print("python list",py_list*2)

[1 4 5 6 7]
[[123   2   3   4]
 [  6   7   8   9]]
python list [1, 2, 3, 4, 1, 2, 3, 4]
python list [2 4 6 8]


In [9]:
import time
start=time.time()
my_list=[i*2 for i in range(10000)]
print(time.time()-start)

import numpy as np
start=time.time()
my_arry=np.arange(100000)*2
print(time.time()-start)


0.002752542495727539
0.002155303955078125


creating array from scratch



In [18]:
import numpy as np
zero=np.zeros((3,4))
print(zero)

one=np.ones((2,3))
print(one)

full=np.full((2,3),"*")
print(full)

random=np.random.random((2,3))
print(random)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[['*' '*' '*']
 ['*' '*' '*']]
[[0.09803614 0.19655361 0.58817357]
 [0.83308658 0.81641987 0.73362803]]


numpy array operation 

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print("with slicing",arr[2:8])
arr=np.array([1,2,3,4,5,6,7,8,9])
print("with slicing with step",arr[2:8:2])
arr=np.array([1,2,3,4,5,6,7,8,9])
print("negative silicing",arr[-3])
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("in 2d arry",arr[2,2])
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("in 2d array with no row define",arr[:,1])

with slicing [3 4 5 6 7 8]
with slicing with step [3 5 7]
negative silicing 7
in 2d arry 9
in 2d array with no row define [2 5 8]


sorting

In [20]:
import numpy as np
arr=np.array([1,2,6,5,8,1,2,2,3,0,9])
print("sorting",np.sort(arr))
arr=np.array([[1,4,5],[4,7,8],[7,2,3]])
print("sorting by columns",np.sort(arr,axis=0))

# even numbers
arr=np.array([1,2,3,4,5,6,7,8,9,10])
number=arr[arr%2==0]
print("even number",number)

# add mask on even number
mask=number>5
print("mask in even number ",number[mask])

# indexts
ind=[1,2,3]
print("even number with mask with index",number[ind])


sorting [0 1 1 2 2 2 3 5 6 8 9]
sorting by columns [[1 2 3]
 [4 4 5]
 [7 7 8]]
even number [ 2  4  6  8 10]
mask in even number  [ 6  8 10]
even number with mask with index [4 6 8]


fancy indexing VS np.where()

In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
ind = [0, 2, 4]
print(arr[ind])
where=np.where(arr>10)
print(arr[where])

result = np.where(arr > 4, arr * 2, arr)
print(result)



[10 30 50]
[20 30 40 50]
[ 20  40  60  80 100]
